include:
  - board: mwave_33
    snippet: studio-rpc-usb-uart
    artifact-name: 4r0x0-mac
    cmake-args: -DKEYMAP_FILE=/tmp/zmk-config/config/mwave_33_mac.keymap -DCONFIG_ZMK_STUDIO=y
  - board: mwave_33
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y -DCONFIG_ZMK_STUDIO=y
    artifact-name: settings-reset
